### ISSUE TITLE
cp does not work

### ISSUE THREAD

**Issue by pcav** [kartoza/docker-qgis-desktop#13]
buils.sh fails on Debian (possibly because of the lack of sud for normal user) with:

{{{
Step 15 : RUN apt-get remove `dpkg -l | grep -e \-dev | grep -v sed
's/ii//g'     | sed 's/rc//g' | sed 's/^ *//;s/ *$//'     | sed 's/ \+
/\t/g' | cut -f 1`
 ---> Running in 2aa889080bde
grep: s/ii//g: No such file or directory
}}}
then
{{{
Successfully built 3319cbc9f1e7
[sudo] password di paolo:
cp: impossibile eseguire stat di 'run-qgis-2.8-in-docker.sh': File o
directory non esistente
cp: impossibile eseguire stat di 'QGIS-2.8.Docker.desktop': File o
directory non esistente
}}}
in fact, 
run-qgis-2.8-in-docker.sh and sudo cp QGIS-2.8.Docker.desktop are not found in 2.8/

**Comment by rduivenvoorde** [comment]
Hi Paolo,

if I'm right, you are building the image yourself using the Docker file? That is you did a checkout and ran ./build.sh ?

I tried this out here locally, and hit some errors too, I've fixed them and put them in my fork (at least in the master). Will do a PR for here: https://github.com/kartoza/docker-qgis-desktop/pull/14

Being asked for root pass word is actually the end of the build script, and asking you to install some desktop icons..., but because the actual build failed these (and the run-qgis-master-in-docker.sh neither)...

@timlinux I think it would be nice to let the user choose to do the sudo parts or not. Personally I do not want/need those application shortcuts, so in build.sh AFTER the build ask the builder/user the question: 
"Do you want desktop icons installed (need root) or do you are you OK with the command line"
"For Desktop icons press Y, for cli press N"
or somethink like that.

It would be cool do start a python3/Qt5 build too ...

I'm doing that also here,

**Comment by timlinux** [comment]
@rduivenvoorde 

> @timlinux I think it would be nice to let the user choose to do the sudo parts or not. Personally I do not want/need those application shortcuts, so in build.sh AFTER the build ask the builder/user the question: 
> "Do you want desktop icons installed (need root) or do you are you OK with the command line"
> "For Desktop icons press Y, for cli press N"

Yeah good idea - I can do that.

> It would be cool do start a python3/Qt5 build too ...

Yup its on my todo list :-)
