### ISSUE TITLE
How to enable python plugin support?

### ISSUE THREAD

**Issue by tino** [kartoza/docker-qgis-desktop#15]
I currently only see 17 plugins listed, and none of the normal web plugins. The Plugins > Settings tab says: "... No Python support detected ...". How could I enable that? Would that require a rebuild with some different settings?

**Comment by luipir** [comment]
too generic issue, can you give more info about what docker container did you build?

**Comment by tino** [comment]
I didn't build. I just pulled the latest from the hub

**Comment by luipir** [comment]
wel... but what did you pull?

**Comment by tino** [comment]
I'm sorry, I am not aware of anything else to pull than `docker pull kartoza/qgis-desktop`? (Which automatically pulls `latest`). 

Hmm, I now see that that tag is 5 months old. Most of your new build are apparently failing: https://hub.docker.com/r/kartoza/qgis-desktop/builds/

I followed this guide if that matters: http://kartoza.com/how-to-run-a-linux-gui-application-on-osx-using-docker/

**Comment by timlinux** [comment]
Please note that the current auto build keeps failing because of timeouts while fetching apt packages. There is not much I can do about it other than building manually and then pushing to the docker hub (but then we lose auto updates when there are security fixes). I am still looking for a solution to this...

**Comment by timlinux** [comment]
I have pushed new images for all recent versions of QGIS
