### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by serkanh** [kartoza/docker-qgis-desktop#2]
Looks like in the instructions there is a simple error. Line should be changed to 
"__sudo chmod +x /usr/local/bin/run-qgis-in-docker.sh__".

"sudo cp run-qgis-in-docker.sh /usr/local/bin
__sudo chmod +x ${HOME}/bin/run-qgis-in-docker.sh__
sudo cp QGIS-2.4.Docker.desktop /usr/share/applications/
sudo cp qgis-icon-60x60.png /usr/local"

**Comment by martyclark** [comment]
Hi Tim,

Thanks for putting this together, really useful. Quick question: I have another (higher) version of QGIS installed on my host machine (2.10). The docker container versions uses the same settings/home directory and plugins. This is great except:

1) Some of the plugins I have installed are for higher than QGIS 2.9 so won't work with the docker version (qGIS 2.4)
2) I can connect to postgis databases running on my host, but I have to manually change the connection information every time. For example, on my native QGIS 2.10 install postgis connects to 'localhost' whereas I have to change the host to my IP address for the docker version. Vice versa when I then use QGIS 2.10 on my host and try to connect to the same database I have to manually edit the connection information again. Not exactly a deal breaker I know!

is there a way to use separate plugins folders/settings for the docker version?

Cheers

Marty

**Comment by timlinux** [comment]
Hi @martyclark 

Sorry for the very long delay in replying....trying to clean up the tickets here:

> 1) Some of the plugins I have installed are for higher than QGIS 2.9 so won't work with the docker version (qGIS 2.4)

There are now tagged versions for:

* 2.10  
* 2.12  
* 2.14 
* 2.6  
* 2.8 
* master

Sorry no 2.4 but if you give me a patch for it I will add it.

> 2) I can connect to postgis databases running on my host, but I have to manually change the connection information every time. For example, on my native QGIS 2.10 install postgis connects to 'localhost' whereas I have to change the host to my IP address for the docker version. Vice versa when I then use QGIS 2.10 on my host and try to connect to the same database I have to manually edit the connection information again. Not exactly a deal breaker I know!

I suggest to use PG Service files so that you can alias the db with the same name regardless of the context you are in.

> is there a way to use separate plugins folders/settings for the docker version?

You can modify the start script so that it does not mount your whole home directory. Its not really a design intent to support multiple different .qgis2 directories, but with a little script tweaking it should be possible.

Thanks for your interest!
