### ISSUE TITLE
docker container fails to run

### ISSUE THREAD

**Issue by martyclark** [kartoza/docker-qgis-desktop#5]
Hi,

I had been playing around with your excellent docker image of QGIS but lately I've been having some issues getting this docker container to run. I started receiving the error messages that the container was in use, so I used the `docker ps -a` command to find held containers and then removed them with `docker rm [container id].

This didn't resolve the issue so I removed the image, and rebuilt it from your instructions. Everything seemed to go fine, but I'm now getting the following error message when I attempt to run docker using:
`sudo docker run --rm --name="qgis-desktop-2-4"     -i -t     -v ${HOME}:/home/${USER}     -v /tmp/.X11-unix:/tmp/.X11-unix     -e DISPLAY=unix$DISPLAY     kartoza/qgis-desktop:latest`

error message:
`useradd: warning: the home directory already exists.
Not copying any file from skel directory into it.
bash: /usr/bin/qgis: No such file or directory`

I've pasted the contents of my /var/log/upstart/docker.log file here: @http://nnmm.nl/?5s5

I'm running Ubuntu 14.04 btw.

Thanks

Marty

p.s. let me know if you want me to provide any other logs/details

**Comment by timlinux** [comment]
Hi @martyclark 

Can you tell me if you are pulling the images from hub.docker.com or building yourself?

I spent some time over the weekend revising the docker recipes - including switching them over to use a Debian base image rather. See https://hub.docker.com/r/kartoza/qgis-desktop/tags/ for available tags.

The develop (which loosely tracks QGIS master - whenever I trigger a build), 2.8.2, 2.8.3 and 2.10 builds should all be using the new recipe. Or otherwise checkout the 2.10 branch from this repo and try to built it locally.

Thanks

Regards

Tim

**Comment by martyclark** [comment]
Hey Tim,

I was just pulling your image from the repo. Will check out your the new
recipes and feedback!

Cheers

Marty

**Comment by timlinux** [comment]
This should not be an issue any more with the latest builds. Please reopen if the issue persists.
